CREATE TABLE employee_roles
(
    employee_id INTEGER NOT NULL,
    role_id     INTEGER NOT NULL,
    CONSTRAINT pk_employee_roles PRIMARY KEY (employee_id, role_id)
);

CREATE TABLE employees
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    last_name     VARCHAR(255),
    email         VARCHAR(255),
    username      VARCHAR(255),
    password      VARCHAR(255),
    department_id INTEGER,
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

ALTER TABLE employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES public.departments (id);

ALTER TABLE employee_roles
    ADD CONSTRAINT fk_emprol_on_employee FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE employee_roles
    ADD CONSTRAINT fk_emprol_on_role FOREIGN KEY (role_id) REFERENCES public.roles (id);

CREATE TABLE public.departments
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    department_name VARCHAR(255),
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

CREATE TABLE public.roles
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);